sudo: required
dist: trusty
language: java
jdk:
  - oraclejdk8

cache:
   directories:
   - $HOME/.m2
   - grakn-dashboard/node_modules

notifications:
  slack: grakn:RbxoPzX267spGT4cgmoGLMpT

env:
  global:
    - TEST_PROFILE=tinker
  matrix:
    - TEST_DIR=ai.grakn.test.migration.export
    - TEST_DIR=ai.grakn.test.migration.json
    - TEST_DIR=ai.grakn.test.migration.owl
    - TEST_DIR=ai.grakn.test.migration.sql
install: mvn install -T 2.5C -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
    - mvn test jacoco:report -DfailIfNoTests=false -P $TEST_PROFILE -Dtest=$TEST_DIR
    - bash <(curl -s https://codecov.io/bash)
before_install:
  - npm install -g npm
